# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  imageName: 'jwt:$(build.buildId)'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Running tests'
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Collection code coverage'
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

#- script: dotnet build --configuration $(buildConfiguration)
#  displayName: 'Building .NET project'

- script: docker build -f JWT.API/Dockerfile -t $(imageName) .
  displayName: 'Building docker container'