version: '3'
services:
  database:
    image: postgres:11
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRE_PASSWORD: password123
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - network

volumes:
  pgdata:
networks:
  network:
     driver: bridge