version: '3'
services:
  api:
    #restart: always
    image: jwt_api:latest
    expose:
      - "5000"
    build:
      context: .
      dockerfile: DockerFile
  proxy:
    build:
      context: JWT.Nginx
      dockerfile: DockerFile
    ports:
      - "8080:8080"
    links:
    - api